<?php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;

class ListUsers extends ListRecords
{
    public int $previousCount = 0;

    protected static string $resource = UserResource::class;

    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub
        $this->previousCount = 0;
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    public function render(): View
    {
        $total = $this->getAllTableRecordsCount();

        if ($this->previousCount > 0 && $this->previousCount !== $total) {
            // fire event
            $this->dispatch('new-created', ['prev' => $this->previousCount, 'new' => $total, 'audio' => url('noti.wav')]);
        }

        $this->previousCount = $total;

        return parent::render(); // TODO: Change the autogenerated stub
    }
}
